name: Deploy to IONOS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Deploy via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.SFTP_USERNAME }}
          server: ${{ secrets.SFTP_HOST }}
          port: 22
          password: ${{ secrets.SFTP_PASSWORD }}
          local_path: './*'
          remote_path: '/public'
          sftp_only: true
          exclude: '["assets/images/students/*", "assets/videos/students/*", ".git*", ".github", "README.md", "node_modules"]'
